### ISSUE TITLE
Simple WatchDog Object has no attribute printEpochs

### ISSUE THREAD

**Issue by JDuskey** [robotpy/robotpy-wpilib-utilities#143] opened 2019-03-21 20:44 UTC
Our code is crashing during autonomous with the above stated error.

**Comment by virtuald** [comment] 2019-03-21 21:41
I'm guessing this is a duplicate of #142 ? You have 2019.0.8 installed, you should install robotpy-wpilib-utilities 2019.0.9 and it'll go away.

**Closed by virtuald** 2019-03-21 21:41 UTC
